CREATE TABLE IF NOT EXISTS WONDERHOY(
    HEROAIMUEMUOTORIEMUISMININGUSUMAIIRU TEXT,
    EMUOTORI TEXT,
    WAHAHAHAH TEXT,
    WAWAN TEXT,
    BOOURGOURS TEXT,
    EMUBIRDWHAR TEXT,
    KAGAMINEREN REAL
);
INSERT INTO WONDERHOY(HEROAIMUEMUOTORIEMUISMININGUSUMAIIRU,EMUOTORI,WAHAHAHAH,BOOURGOURS,EMUBIRDWHAR,KAGAMINEREN)
VALUES
    ("1","OTORI","WONDERHOY","KONICHIWONDERHOY","1811334",111),
    ("2","EMU","RIPITOAFUTAEMU","WAWANWANDAHOI","143",222),
    ("3","TSUCACA","TEMPA","HEYDATSNOTMAYNAME","144",333),
    ("4","TOUHOU","BADAPPLE","ERINERIN","1238388182181929222919",444),
    ("5","EBURIDEI","POTATOISU","BEJITABURU","10101222333445566778899900",555);

SELECT COUNT (HEROAIMUEMUOTORIEMUISMININGUSUMAIIRU) AS EMU
FROM WONDERHOY ;
SELECT AVG(KAGAMINEREN) AS LEN
FROM WONDERHOY ;
SELECT SUM(KAGAMINEREN) AS A_REN
FROM WONDERHOY ;